### ISSUE TITLE
MissingTradeSkillsList blocked Interface Action - SafeQueue Didn't pop

### ISSUE THREAD

**Issue by boktai1000** [jordonwow/safequeue#12]
I'll try and gather more information in my taint log, but the SafeQueue prompt didn't pop up and I got the Blizzard text asking me to disable the addon. Link to the addon in question below - it is also not consistent behavior when it does happen.

https://www.curseforge.com/wow/addons/missing-tradeskills-list

**Comment by Mushoz** [comment]
Same thing is happening for me, and most of the occurrences are indeed also with Missing Tradeskills List for me. Having said that, I have also had other addons produce the same issue. For example, questie has done the same in the past (but much less frequent than MTL)
