### ISSUE TITLE
unexpected symbol

### ISSUE THREAD

**Issue by Hitsuwalker** [jordonwow/safequeue#13]
Hello can someone help me to fix this problem ?
I have since a long time!
It would be nice if I can fix it by any way

Message: Interface\AddOns\SafeQueue\SafeQueue.lua:1: unexpected symbol
Time: Wed Sep  1 20:18:55 2021
Count: 3

**Comment by jordonwow** [comment]
sounds like you downloaded a corrupt version, try installing through Curse
