### ISSUE TITLE
!BlizzardRaidFramesFix

### ISSUE THREAD

**Issue by Tenies** [jordonwow/safequeue#16]
Latest version works great, even if i get the error i can join my BGs/Arenas but i keep getting error from "!BlizzardRaidFramesFix".
Is it possible to do something about this?

**Comment by Tenies** [comment]
Also "LoseControl" give me many errors.

**Comment by jordonwow** [comment]
Can you paste the error you're receiving here please

**Comment by zmmcyzmmcy** [comment]
14x [ADDON_ACTION_FORBIDDEN] 插件 '!BlizzardRaidFramesFix' 尝试调用保护功能 'GuildControlSetRank()'。
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GuildControlSetRank'
[string "@FrameXML\FriendsFrame.lua"]:2498: in function `func'
[string "@FrameXML\UIDropDownMenu.lua"]:960: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
