### ISSUE TITLE
SafeQueue not showing in CurseForge client search results

### ISSUE THREAD

**Issue by zhranj** [jordonwow/safequeue#4]
I know this is not an issue with this addon, but you might want to investigate why it does not pop up in search results. I've confirmed this is not just me, a lot of people confirmed to not finding it on twitch.tv.

![image](https://user-images.githubusercontent.com/733556/101881016-1d6fd900-3b94-11eb-8ecd-5d7a473d4cb4.png)

**Comment by jordonwow** [comment]
Thanks, it should be showing up now
