### ISSUE TITLE
Game Version: 1.13.5 not working for shadowlands

### ISSUE THREAD

**Issue by thedurko** [jordonwow/safequeue#6]
Hi there,

I downloaded Game Version: 1.13.5 from https://www.curseforge.com/wow/addons/safequeue (only version I could find), but it seems not to be working for Shadowlands. I deployed the addon the usual way (unzip and paste the whole folder into the Addons WoW folder). Is there a reason why this is not working please? Thanks.

**Comment by jordonwow** [comment]
Sorry, this addon is only for Classic and Burning Crusade Classic
