### ISSUE TITLE
Since 2.5.1 Questie is sometimes blocking the enter battle button

### ISSUE THREAD

**Issue by Nillx** [jordonwow/safequeue#8]
Noticed that even with the addon installed i get the enter battle error. It says that Questie is blocking the function. Manually clicking on the BG icon and selecting Enter Battle does nothing. I have to reload my UI to enter.

**Comment by Knakriktsur** [comment]
I have the same problem, not only with Questie. Will add the addons names. TomTom is another example.
When Questie has this reload ui oesn`t help :/ Reloaded about 4 times, than que was gone and I had to start from beginning :/

**Comment by Knakriktsur** [comment]
Other addons listes to block:
Questie
TomTom
HandyNotes
Nova World Buffs
Ok to post here or ne request for each?

**Comment by jordonwow** [comment]
Please reopen if you still experience this issue with the latest release

**Comment by Leseulunik** [comment]
Still the same issu with others addons:
Slashfour
Sortgroup
